# Generated by Django 4.2.13 on 2024-05-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100, verbose_name='Book author')),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('pos_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
