# Generated by Django 4.2.13 on 2024-06-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_review_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
