# Generated by Django 4.2.13 on 2024-07-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_review_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('founded', models.DateField()),
                ('website', models.URLField()),
                ('address', models.JSONField()),
                ('active', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=5)),
                ('books', models.ManyToManyField(to='myapp.book')),
            ],
        ),
    ]
