# Generated by Django 4.2.16 on 2025-01-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_book_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='detailreview',
            options={'ordering': ['-id'], 'verbose_name': 'Detail Review', 'verbose_name_plural': 'Details Reviews'},
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
