# Generated by Django 4.2.16 on 2025-01-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_book_options_alter_detailreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailreview',
            options={'ordering': ['id'], 'verbose_name': 'Detail Review', 'verbose_name_plural': 'Details Reviews'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['id'], 'verbose_name': 'Label', 'verbose_name_plural': 'Labels'},
        ),
        migrations.AlterField(
            model_name='publisher',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=500),
        ),
    ]
