# Generated by Django 4.2.18 on 2025-02-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='flag',
            field=models.ImageField(upload_to='flags/'),
        ),
    ]
