# Generated by Django 4.2.18 on 2025-02-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_book_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
