from .book import BookListCreateAPIView, BookDetailAPIView
from .detail_review import DetailReviewListCreateAPIView, DetailReviewDetailAPIView
from .label import LabelListCreateAPIView, LabelDetailAPIView
from .publisher import PublisherListCreateAPIView, PublisherDetailAPIView
from .review import ReviewListCreateAPIView, ReviewDetailAPIView
from .language import LanguageListCreateAPIView, LanguageDetailAPIView